### ISSUE TITLE
Install swift-mailer using apt

### ISSUE THREAD

**Issue by Dave-McCraw** [Dave-McCraw/pkg-emoncms#3]
At the moment, installation instructions still require Swift Mailer to be pulled from PEAR / PECL but it is available (on `sid`) as the package `libphp-swiftmailer` [[1]](https://packages.debian.org/sid/libphp-swiftmailer).

Rather than ask  people to expose `sid`, it might be better to host this package from our own emon-repo on s3, and simplify the installation one step further by making it a debian control dependency.

**Comment by lafrech** [comment]
It is also available in testing, and in stable with an earlier version (4.1.5):

http://packages.qa.debian.org/libp/libphp-swiftmailer.html

**Comment by Dave-McCraw** [comment]
Excellent, thanks for the catch. That should make it very simple. 

Just the redis module to tackle now then :-) 

On 2014-03-26 10:05, Jérôme Lafréchoux wrote: 

> It is also available in testing, and in stable with an earlier version (4.1.5): 
> 
> http://packages.qa.debian.org/libp/libphp-swiftmailer.html [1] 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].

## Links:

[1] http://packages.qa.debian.org/libp/libphp-swiftmailer.html
[2]
https://github.com/Dave-McCraw/pkg-emoncms/issues/3#issuecomment-38666539

**Comment by lafrech** [comment]
There is redis stuff in testing, even some in stable, but I guess php5-redis would be needed and it is only in testing.

I suppose you'll have to maintain at least a Wheezy version, but perhaps a Jessie as well. In this case, you can try to backport needed packages to your Wheezy repo, and you can rely on the official repos for Jessie.

The backport might not be obvious. For instance, php5-redis. You can't just copy it, since the Jessie version depends on libc6 >= 2.14 and Wheezy has 2.13.
