### ISSUE TITLE
Debian package and nginx

### ISSUE THREAD

**Issue by BlackEdder** [Dave-McCraw/pkg-emoncms#5]
Would it be possible to have the debian package not depend on apache? I have nginx already running on my raspberry pi and would prefer not to install apache2. I am not too familiar with debian packages, but would think it should be possible to depend on nginx or apache instead of only on apache?

(This issue originated as emoncms/emoncms#209 and was moved here on @Dave-McCraw request.)

**Comment by Dave-McCraw** [comment]
Hi,

Presently when you install emoncms from APT it configures apache to serve the site. Although I could remove the package dependency, it won't work on nginx without some kind of equivalent configuration (and you probably wouldn't want the apache stuff). 

I don't really want to start maintaining multiple platforms, because as you can imagine this wouldn't scale- there are a lot of possible servers that people can run, and then there's the question of people asking to run postgres instead of mysql, and so on. Too much work for my modest time budget - I'd rather keep the debian package aligned with the core offering.

There are a couple of options: if you want to start supporting an nginx port of emoncms we could talk about possible ways you could start contributing by packing up your own configuration and deployment. However, you'd need to be building and uploading this whenever a new version of emoncms is released, which can be quite a time burden (not to mention supporting other nginx requests, I guess?)

Alternatively, you can just satisfy the dependency manually using [equivs](http://shallowsky.com/blog/linux/install/blocking-deb-dependencies.html) so that apt-get doesn't complain, and roll your own local setup.

thanks,

D.

**Comment by BlackEdder** [comment]
Hi,

I understand that you're not keen on taking on the responsibility for nginx support and I'm afraid my nginx knowledge is not good enough for me to support nginx configuration. Currently, I'm actually using emoncms.org. If I decide to spend the time figuring out nginx properly then I might come back to this issue, but I'll close this issue for now.

Thanks for the link on equivs. That will be very helpful.
